// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  CertificateDeleteCertificatesByIdErrors,
  CertificateDeleteCertificatesByIdRequest,
  CertificateDeleteCertificatesByIdResponses,
  CertificateGetCertificatesByIdErrors,
  CertificateGetCertificatesByIdRequest,
  CertificateGetCertificatesByIdResponses,
  CertificateGetCertificatesErrors,
  CertificateGetCertificatesRequest,
  CertificateGetCertificatesResponses,
  CertificatePostCertificatesErrors,
  CertificatePostCertificatesRequest,
  CertificatePostCertificatesResponses,
  CertificatePutCertificatesByIdErrors,
  CertificatePutCertificatesByIdRequest,
  CertificatePutCertificatesByIdResponses,
  ContentCreatorDeleteContentCreatorsByIdErrors,
  ContentCreatorDeleteContentCreatorsByIdRequest,
  ContentCreatorDeleteContentCreatorsByIdResponses,
  ContentCreatorGetContentCreatorsByIdErrors,
  ContentCreatorGetContentCreatorsByIdRequest,
  ContentCreatorGetContentCreatorsByIdResponses,
  ContentCreatorGetContentCreatorsErrors,
  ContentCreatorGetContentCreatorsRequest,
  ContentCreatorGetContentCreatorsResponses,
  ContentCreatorPostContentCreatorsErrors,
  ContentCreatorPostContentCreatorsRequest,
  ContentCreatorPostContentCreatorsResponses,
  ContentCreatorPutContentCreatorsByIdErrors,
  ContentCreatorPutContentCreatorsByIdRequest,
  ContentCreatorPutContentCreatorsByIdResponses,
  ContentTypeBuilderGetComponentsByUidErrors,
  ContentTypeBuilderGetComponentsByUidRequest,
  ContentTypeBuilderGetComponentsByUidResponses,
  ContentTypeBuilderGetComponentsErrors,
  ContentTypeBuilderGetComponentsRequest,
  ContentTypeBuilderGetComponentsResponses,
  ContentTypeBuilderGetContentTypesByUidErrors,
  ContentTypeBuilderGetContentTypesByUidRequest,
  ContentTypeBuilderGetContentTypesByUidResponses,
  ContentTypeBuilderGetContentTypesErrors,
  ContentTypeBuilderGetContentTypesRequest,
  ContentTypeBuilderGetContentTypesResponses,
  CourseCategoryDeleteCourseCategoriesByIdErrors,
  CourseCategoryDeleteCourseCategoriesByIdRequest,
  CourseCategoryDeleteCourseCategoriesByIdResponses,
  CourseCategoryGetCourseCategoriesByIdErrors,
  CourseCategoryGetCourseCategoriesByIdRequest,
  CourseCategoryGetCourseCategoriesByIdResponses,
  CourseCategoryGetCourseCategoriesErrors,
  CourseCategoryGetCourseCategoriesRequest,
  CourseCategoryGetCourseCategoriesResponses,
  CourseCategoryPostCourseCategoriesErrors,
  CourseCategoryPostCourseCategoriesRequest,
  CourseCategoryPostCourseCategoriesResponses,
  CourseCategoryPutCourseCategoriesByIdErrors,
  CourseCategoryPutCourseCategoriesByIdRequest,
  CourseCategoryPutCourseCategoriesByIdResponses,
  CourseDeleteCoursesByIdErrors,
  CourseDeleteCoursesByIdRequest,
  CourseDeleteCoursesByIdResponses,
  CourseGetCoursesByIdErrors,
  CourseGetCoursesByIdRequest,
  CourseGetCoursesByIdResponses,
  CourseGetCoursesErrors,
  CourseGetCoursesRequest,
  CourseGetCoursesResponses,
  CoursePostCoursesErrors,
  CoursePostCoursesRequest,
  CoursePostCoursesResponses,
  CoursePutCoursesByIdErrors,
  CoursePutCoursesByIdRequest,
  CoursePutCoursesByIdResponses,
  CourseSelectionDeleteCourseSelectionsByIdErrors,
  CourseSelectionDeleteCourseSelectionsByIdRequest,
  CourseSelectionDeleteCourseSelectionsByIdResponses,
  CourseSelectionGetCourseSelectionsByIdErrors,
  CourseSelectionGetCourseSelectionsByIdRequest,
  CourseSelectionGetCourseSelectionsByIdResponses,
  CourseSelectionGetCourseSelectionsErrors,
  CourseSelectionGetCourseSelectionsRequest,
  CourseSelectionGetCourseSelectionsResponses,
  CourseSelectionPostCourseSelectionsErrors,
  CourseSelectionPostCourseSelectionsRequest,
  CourseSelectionPostCourseSelectionsResponses,
  CourseSelectionPutCourseSelectionsByIdErrors,
  CourseSelectionPutCourseSelectionsByIdRequest,
  CourseSelectionPutCourseSelectionsByIdResponses,
  ExerciseDeleteExercisesByIdErrors,
  ExerciseDeleteExercisesByIdRequest,
  ExerciseDeleteExercisesByIdResponses,
  ExerciseGetExercisesByIdErrors,
  ExerciseGetExercisesByIdRequest,
  ExerciseGetExercisesByIdResponses,
  ExerciseGetExercisesErrors,
  ExerciseGetExercisesRequest,
  ExerciseGetExercisesResponses,
  ExerciseOptionDeleteExerciseOptionsByIdErrors,
  ExerciseOptionDeleteExerciseOptionsByIdRequest,
  ExerciseOptionDeleteExerciseOptionsByIdResponses,
  ExerciseOptionGetExerciseOptionsByIdErrors,
  ExerciseOptionGetExerciseOptionsByIdRequest,
  ExerciseOptionGetExerciseOptionsByIdResponses,
  ExerciseOptionGetExerciseOptionsErrors,
  ExerciseOptionGetExerciseOptionsRequest,
  ExerciseOptionGetExerciseOptionsResponses,
  ExerciseOptionPostExerciseOptionsErrors,
  ExerciseOptionPostExerciseOptionsRequest,
  ExerciseOptionPostExerciseOptionsResponses,
  ExerciseOptionPutExerciseOptionsByIdErrors,
  ExerciseOptionPutExerciseOptionsByIdRequest,
  ExerciseOptionPutExerciseOptionsByIdResponses,
  ExercisePostExercisesErrors,
  ExercisePostExercisesRequest,
  ExercisePostExercisesResponses,
  ExercisePutExercisesByIdErrors,
  ExercisePutExercisesByIdRequest,
  ExercisePutExercisesByIdResponses,
  FeedbackDeleteFeedbacksByIdErrors,
  FeedbackDeleteFeedbacksByIdRequest,
  FeedbackDeleteFeedbacksByIdResponses,
  FeedbackGetFeedbacksByIdErrors,
  FeedbackGetFeedbacksByIdRequest,
  FeedbackGetFeedbacksByIdResponses,
  FeedbackGetFeedbacksErrors,
  FeedbackGetFeedbacksRequest,
  FeedbackGetFeedbacksResponses,
  FeedbackPostFeedbacksErrors,
  FeedbackPostFeedbacksRequest,
  FeedbackPostFeedbacksResponses,
  FeedbackPutFeedbacksByIdErrors,
  FeedbackPutFeedbacksByIdRequest,
  FeedbackPutFeedbacksByIdResponses,
  I18nGetLocalesErrors,
  I18nGetLocalesRequest,
  I18nGetLocalesResponses,
  LectureDeleteLecturesByIdErrors,
  LectureDeleteLecturesByIdRequest,
  LectureDeleteLecturesByIdResponses,
  LectureGetLecturesByIdErrors,
  LectureGetLecturesByIdRequest,
  LectureGetLecturesByIdResponses,
  LectureGetLecturesErrors,
  LectureGetLecturesRequest,
  LectureGetLecturesResponses,
  LecturePostLecturesErrors,
  LecturePostLecturesRequest,
  LecturePostLecturesResponses,
  LecturePutLecturesByIdErrors,
  LecturePutLecturesByIdRequest,
  LecturePutLecturesByIdResponses,
  PasswordResetTokenDeletePasswordResetTokensByIdErrors,
  PasswordResetTokenDeletePasswordResetTokensByIdRequest,
  PasswordResetTokenDeletePasswordResetTokensByIdResponses,
  PasswordResetTokenGetPasswordResetTokensByIdErrors,
  PasswordResetTokenGetPasswordResetTokensByIdRequest,
  PasswordResetTokenGetPasswordResetTokensByIdResponses,
  PasswordResetTokenGetPasswordResetTokensErrors,
  PasswordResetTokenGetPasswordResetTokensRequest,
  PasswordResetTokenGetPasswordResetTokensResponses,
  PasswordResetTokenPostPasswordResetTokensErrors,
  PasswordResetTokenPostPasswordResetTokensRequest,
  PasswordResetTokenPostPasswordResetTokensResponses,
  PasswordResetTokenPutPasswordResetTokensByIdErrors,
  PasswordResetTokenPutPasswordResetTokensByIdRequest,
  PasswordResetTokenPutPasswordResetTokensByIdResponses,
  PatchStudentResetPasswordUpdateRequest,
  PatchStudentResetPasswordUpdateResponses,
  PostStudentLoginRequest,
  PostStudentLoginResponses,
  PostStudentResetPasswordCodeRequest,
  PostStudentResetPasswordCodeResponses,
  PostStudentResetPasswordRequestRequest,
  PostStudentResetPasswordRequestResponses,
  PostStudentSendVerificationTokenRequest,
  PostStudentSendVerificationTokenResponses,
  PostStudentSignupRequest,
  PostStudentSignupResponses,
  PostStudentVerifyEmailRequest,
  PostStudentVerifyEmailResponses,
  StudentDeleteStudentsByIdErrors,
  StudentDeleteStudentsByIdRequest,
  StudentDeleteStudentsByIdResponses,
  StudentGetStudentsByIdErrors,
  StudentGetStudentsByIdRequest,
  StudentGetStudentsByIdResponses,
  StudentGetStudentsErrors,
  StudentGetStudentsRequest,
  StudentGetStudentsResponses,
  StudentPostStudentsErrors,
  StudentPostStudentsRequest,
  StudentPostStudentsResponses,
  StudentPutStudentsByIdErrors,
  StudentPutStudentsByIdRequest,
  StudentPutStudentsByIdResponses,
  UploadDeleteFilesByIdErrors,
  UploadDeleteFilesByIdRequest,
  UploadDeleteFilesByIdResponses,
  UploadGetFilesByIdErrors,
  UploadGetFilesByIdRequest,
  UploadGetFilesByIdResponses,
  UploadGetFilesErrors,
  UploadGetFilesRequest,
  UploadGetFilesResponses,
  UploadPostErrors,
  UploadPostRequest,
  UploadPostResponses,
  UserLogDeleteUserLogsByIdErrors,
  UserLogDeleteUserLogsByIdRequest,
  UserLogDeleteUserLogsByIdResponses,
  UserLogGetUserLogsByIdErrors,
  UserLogGetUserLogsByIdRequest,
  UserLogGetUserLogsByIdResponses,
  UserLogGetUserLogsErrors,
  UserLogGetUserLogsRequest,
  UserLogGetUserLogsResponses,
  UserLogPostUserLogsErrors,
  UserLogPostUserLogsRequest,
  UserLogPostUserLogsResponses,
  UserLogPutUserLogsByIdErrors,
  UserLogPutUserLogsByIdRequest,
  UserLogPutUserLogsByIdResponses,
  UsersPermissionsDeleteRolesByRoleErrors,
  UsersPermissionsDeleteRolesByRoleRequest,
  UsersPermissionsDeleteRolesByRoleResponses,
  UsersPermissionsDeleteUsersByIdErrors,
  UsersPermissionsDeleteUsersByIdRequest,
  UsersPermissionsDeleteUsersByIdResponses,
  UsersPermissionsGetAuthByProviderCallbackErrors,
  UsersPermissionsGetAuthByProviderCallbackRequest,
  UsersPermissionsGetAuthByProviderCallbackResponses,
  UsersPermissionsGetAuthEmailConfirmationErrors,
  UsersPermissionsGetAuthEmailConfirmationRequest,
  UsersPermissionsGetAuthEmailConfirmationResponses,
  UsersPermissionsGetConnectErrors,
  UsersPermissionsGetConnectRequest,
  UsersPermissionsGetPermissionsErrors,
  UsersPermissionsGetPermissionsRequest,
  UsersPermissionsGetPermissionsResponses,
  UsersPermissionsGetRolesByIdErrors,
  UsersPermissionsGetRolesByIdRequest,
  UsersPermissionsGetRolesByIdResponses,
  UsersPermissionsGetRolesErrors,
  UsersPermissionsGetRolesRequest,
  UsersPermissionsGetRolesResponses,
  UsersPermissionsGetUsersByIdErrors,
  UsersPermissionsGetUsersByIdRequest,
  UsersPermissionsGetUsersByIdResponses,
  UsersPermissionsGetUsersCountErrors,
  UsersPermissionsGetUsersCountRequest,
  UsersPermissionsGetUsersCountResponses,
  UsersPermissionsGetUsersErrors,
  UsersPermissionsGetUsersMeErrors,
  UsersPermissionsGetUsersMeRequest,
  UsersPermissionsGetUsersMeResponses,
  UsersPermissionsGetUsersRequest,
  UsersPermissionsGetUsersResponses,
  UsersPermissionsPostAuthChangePasswordErrors,
  UsersPermissionsPostAuthChangePasswordRequest,
  UsersPermissionsPostAuthChangePasswordResponses,
  UsersPermissionsPostAuthForgotPasswordErrors,
  UsersPermissionsPostAuthForgotPasswordRequest,
  UsersPermissionsPostAuthForgotPasswordResponses,
  UsersPermissionsPostAuthLocalErrors,
  UsersPermissionsPostAuthLocalRegisterErrors,
  UsersPermissionsPostAuthLocalRegisterRequest,
  UsersPermissionsPostAuthLocalRegisterResponses,
  UsersPermissionsPostAuthLocalRequest,
  UsersPermissionsPostAuthLocalResponses,
  UsersPermissionsPostAuthLogoutErrors,
  UsersPermissionsPostAuthLogoutRequest,
  UsersPermissionsPostAuthRefreshErrors,
  UsersPermissionsPostAuthRefreshRequest,
  UsersPermissionsPostAuthResetPasswordErrors,
  UsersPermissionsPostAuthResetPasswordRequest,
  UsersPermissionsPostAuthResetPasswordResponses,
  UsersPermissionsPostAuthSendEmailConfirmationErrors,
  UsersPermissionsPostAuthSendEmailConfirmationRequest,
  UsersPermissionsPostAuthSendEmailConfirmationResponses,
  UsersPermissionsPostRolesErrors,
  UsersPermissionsPostRolesRequest,
  UsersPermissionsPostRolesResponses,
  UsersPermissionsPostUsersErrors,
  UsersPermissionsPostUsersRequest,
  UsersPermissionsPostUsersResponses,
  UsersPermissionsPutRolesByRoleErrors,
  UsersPermissionsPutRolesByRoleRequest,
  UsersPermissionsPutRolesByRoleResponses,
  UsersPermissionsPutUsersByIdErrors,
  UsersPermissionsPutUsersByIdRequest,
  UsersPermissionsPutUsersByIdResponses,
  VerificationTokenDeleteVerificationTokensByIdErrors,
  VerificationTokenDeleteVerificationTokensByIdRequest,
  VerificationTokenDeleteVerificationTokensByIdResponses,
  VerificationTokenGetVerificationTokensByIdErrors,
  VerificationTokenGetVerificationTokensByIdRequest,
  VerificationTokenGetVerificationTokensByIdResponses,
  VerificationTokenGetVerificationTokensErrors,
  VerificationTokenGetVerificationTokensRequest,
  VerificationTokenGetVerificationTokensResponses,
  VerificationTokenPostVerificationTokensErrors,
  VerificationTokenPostVerificationTokensRequest,
  VerificationTokenPostVerificationTokensResponses,
  VerificationTokenPutVerificationTokensByIdErrors,
  VerificationTokenPutVerificationTokensByIdRequest,
  VerificationTokenPutVerificationTokensByIdResponses,
} from "./types.gen";
import {
  zCertificateDeleteCertificatesByIdRequest,
  zCertificateGetCertificatesByIdRequest,
  zCertificateGetCertificatesRequest,
  zCertificatePostCertificatesRequest,
  zCertificatePutCertificatesByIdRequest,
  zContentCreatorDeleteContentCreatorsByIdRequest,
  zContentCreatorGetContentCreatorsByIdRequest,
  zContentCreatorGetContentCreatorsRequest,
  zContentCreatorPostContentCreatorsRequest,
  zContentCreatorPutContentCreatorsByIdRequest,
  zContentTypeBuilderGetComponentsByUidRequest,
  zContentTypeBuilderGetComponentsRequest,
  zContentTypeBuilderGetContentTypesByUidRequest,
  zContentTypeBuilderGetContentTypesRequest,
  zCourseCategoryDeleteCourseCategoriesByIdRequest,
  zCourseCategoryGetCourseCategoriesByIdRequest,
  zCourseCategoryGetCourseCategoriesRequest,
  zCourseCategoryPostCourseCategoriesRequest,
  zCourseCategoryPutCourseCategoriesByIdRequest,
  zCourseDeleteCoursesByIdRequest,
  zCourseGetCoursesByIdRequest,
  zCourseGetCoursesRequest,
  zCoursePostCoursesRequest,
  zCoursePutCoursesByIdRequest,
  zCourseSelectionDeleteCourseSelectionsByIdRequest,
  zCourseSelectionGetCourseSelectionsByIdRequest,
  zCourseSelectionGetCourseSelectionsRequest,
  zCourseSelectionPostCourseSelectionsRequest,
  zCourseSelectionPutCourseSelectionsByIdRequest,
  zExerciseDeleteExercisesByIdRequest,
  zExerciseGetExercisesByIdRequest,
  zExerciseGetExercisesRequest,
  zExerciseOptionDeleteExerciseOptionsByIdRequest,
  zExerciseOptionGetExerciseOptionsByIdRequest,
  zExerciseOptionGetExerciseOptionsRequest,
  zExerciseOptionPostExerciseOptionsRequest,
  zExerciseOptionPutExerciseOptionsByIdRequest,
  zExercisePostExercisesRequest,
  zExercisePutExercisesByIdRequest,
  zFeedbackDeleteFeedbacksByIdRequest,
  zFeedbackGetFeedbacksByIdRequest,
  zFeedbackGetFeedbacksRequest,
  zFeedbackPostFeedbacksRequest,
  zFeedbackPutFeedbacksByIdRequest,
  zI18nGetLocalesRequest,
  zLectureDeleteLecturesByIdRequest,
  zLectureGetLecturesByIdRequest,
  zLectureGetLecturesRequest,
  zLecturePostLecturesRequest,
  zLecturePutLecturesByIdRequest,
  zPasswordResetTokenDeletePasswordResetTokensByIdRequest,
  zPasswordResetTokenGetPasswordResetTokensByIdRequest,
  zPasswordResetTokenGetPasswordResetTokensRequest,
  zPasswordResetTokenPostPasswordResetTokensRequest,
  zPasswordResetTokenPutPasswordResetTokensByIdRequest,
  zPatchStudentResetPasswordUpdateRequest,
  zPostStudentLoginRequest,
  zPostStudentResetPasswordCodeRequest,
  zPostStudentResetPasswordRequestRequest,
  zPostStudentSendVerificationTokenRequest,
  zPostStudentSignupRequest,
  zPostStudentVerifyEmailRequest,
  zStudentDeleteStudentsByIdRequest,
  zStudentGetStudentsByIdRequest,
  zStudentGetStudentsRequest,
  zStudentPostStudentsRequest,
  zStudentPutStudentsByIdRequest,
  zUploadDeleteFilesByIdRequest,
  zUploadGetFilesByIdRequest,
  zUploadGetFilesRequest,
  zUploadPostRequest,
  zUserLogDeleteUserLogsByIdRequest,
  zUserLogGetUserLogsByIdRequest,
  zUserLogGetUserLogsRequest,
  zUserLogPostUserLogsRequest,
  zUserLogPutUserLogsByIdRequest,
  zUsersPermissionsDeleteRolesByRoleRequest,
  zUsersPermissionsDeleteUsersByIdRequest,
  zUsersPermissionsGetAuthByProviderCallbackRequest,
  zUsersPermissionsGetAuthEmailConfirmationRequest,
  zUsersPermissionsGetConnectRequest,
  zUsersPermissionsGetPermissionsRequest,
  zUsersPermissionsGetRolesByIdRequest,
  zUsersPermissionsGetRolesRequest,
  zUsersPermissionsGetUsersByIdRequest,
  zUsersPermissionsGetUsersCountRequest,
  zUsersPermissionsGetUsersMeRequest,
  zUsersPermissionsGetUsersRequest,
  zUsersPermissionsPostAuthChangePasswordRequest,
  zUsersPermissionsPostAuthForgotPasswordRequest,
  zUsersPermissionsPostAuthLocalRegisterRequest,
  zUsersPermissionsPostAuthLocalRequest,
  zUsersPermissionsPostAuthLogoutRequest,
  zUsersPermissionsPostAuthRefreshRequest,
  zUsersPermissionsPostAuthResetPasswordRequest,
  zUsersPermissionsPostAuthSendEmailConfirmationRequest,
  zUsersPermissionsPostRolesRequest,
  zUsersPermissionsPostUsersRequest,
  zUsersPermissionsPutRolesByRoleRequest,
  zUsersPermissionsPutUsersByIdRequest,
  zVerificationTokenDeleteVerificationTokensByIdRequest,
  zVerificationTokenGetVerificationTokensByIdRequest,
  zVerificationTokenGetVerificationTokensRequest,
  zVerificationTokenPostVerificationTokensRequest,
  zVerificationTokenPutVerificationTokensByIdRequest,
} from "./zod.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const certificateGetCertificates = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<CertificateGetCertificatesRequest, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    CertificateGetCertificatesResponses,
    CertificateGetCertificatesErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zCertificateGetCertificatesRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/certificates",
    ...options,
  });
};

export const certificatePostCertificates = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CertificatePostCertificatesRequest, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CertificatePostCertificatesResponses,
    CertificatePostCertificatesErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zCertificatePostCertificatesRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/certificates",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const certificateDeleteCertificatesById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CertificateDeleteCertificatesByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    CertificateDeleteCertificatesByIdResponses,
    CertificateDeleteCertificatesByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zCertificateDeleteCertificatesByIdRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/certificates/{id}",
    ...options,
  });
};

export const certificateGetCertificatesById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CertificateGetCertificatesByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    CertificateGetCertificatesByIdResponses,
    CertificateGetCertificatesByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zCertificateGetCertificatesByIdRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/certificates/{id}",
    ...options,
  });
};

export const certificatePutCertificatesById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CertificatePutCertificatesByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    CertificatePutCertificatesByIdResponses,
    CertificatePutCertificatesByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zCertificatePutCertificatesByIdRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/certificates/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const contentCreatorGetContentCreators = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ContentCreatorGetContentCreatorsRequest, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ContentCreatorGetContentCreatorsResponses,
    ContentCreatorGetContentCreatorsErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zContentCreatorGetContentCreatorsRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/content-creators",
    ...options,
  });
};

export const contentCreatorPostContentCreators = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ContentCreatorPostContentCreatorsRequest, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ContentCreatorPostContentCreatorsResponses,
    ContentCreatorPostContentCreatorsErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zContentCreatorPostContentCreatorsRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/content-creators",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const contentCreatorDeleteContentCreatorsById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ContentCreatorDeleteContentCreatorsByIdRequest,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).delete<
    ContentCreatorDeleteContentCreatorsByIdResponses,
    ContentCreatorDeleteContentCreatorsByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zContentCreatorDeleteContentCreatorsByIdRequest.parseAsync(
        data,
      );
    },
    responseStyle: "data",
    url: "/content-creators/{id}",
    ...options,
  });
};

export const contentCreatorGetContentCreatorsById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ContentCreatorGetContentCreatorsByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ContentCreatorGetContentCreatorsByIdResponses,
    ContentCreatorGetContentCreatorsByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zContentCreatorGetContentCreatorsByIdRequest.parseAsync(
        data,
      );
    },
    responseStyle: "data",
    url: "/content-creators/{id}",
    ...options,
  });
};

export const contentCreatorPutContentCreatorsById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ContentCreatorPutContentCreatorsByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    ContentCreatorPutContentCreatorsByIdResponses,
    ContentCreatorPutContentCreatorsByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zContentCreatorPutContentCreatorsByIdRequest.parseAsync(
        data,
      );
    },
    responseStyle: "data",
    url: "/content-creators/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const courseGetCourses = <ThrowOnError extends boolean = false>(
  options?: Options<CourseGetCoursesRequest, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    CourseGetCoursesResponses,
    CourseGetCoursesErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zCourseGetCoursesRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/courses",
    ...options,
  });
};

export const coursePostCourses = <ThrowOnError extends boolean = false>(
  options: Options<CoursePostCoursesRequest, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CoursePostCoursesResponses,
    CoursePostCoursesErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zCoursePostCoursesRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/courses",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const courseDeleteCoursesById = <ThrowOnError extends boolean = false>(
  options: Options<CourseDeleteCoursesByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    CourseDeleteCoursesByIdResponses,
    CourseDeleteCoursesByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zCourseDeleteCoursesByIdRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/courses/{id}",
    ...options,
  });
};

export const courseGetCoursesById = <ThrowOnError extends boolean = false>(
  options: Options<CourseGetCoursesByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    CourseGetCoursesByIdResponses,
    CourseGetCoursesByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zCourseGetCoursesByIdRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/courses/{id}",
    ...options,
  });
};

export const coursePutCoursesById = <ThrowOnError extends boolean = false>(
  options: Options<CoursePutCoursesByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    CoursePutCoursesByIdResponses,
    CoursePutCoursesByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zCoursePutCoursesByIdRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/courses/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const courseCategoryGetCourseCategories = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<CourseCategoryGetCourseCategoriesRequest, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    CourseCategoryGetCourseCategoriesResponses,
    CourseCategoryGetCourseCategoriesErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zCourseCategoryGetCourseCategoriesRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/course-categories",
    ...options,
  });
};

export const courseCategoryPostCourseCategories = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CourseCategoryPostCourseCategoriesRequest, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CourseCategoryPostCourseCategoriesResponses,
    CourseCategoryPostCourseCategoriesErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zCourseCategoryPostCourseCategoriesRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/course-categories",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const courseCategoryDeleteCourseCategoriesById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CourseCategoryDeleteCourseCategoriesByIdRequest,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).delete<
    CourseCategoryDeleteCourseCategoriesByIdResponses,
    CourseCategoryDeleteCourseCategoriesByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zCourseCategoryDeleteCourseCategoriesByIdRequest.parseAsync(
        data,
      );
    },
    responseStyle: "data",
    url: "/course-categories/{id}",
    ...options,
  });
};

export const courseCategoryGetCourseCategoriesById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CourseCategoryGetCourseCategoriesByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    CourseCategoryGetCourseCategoriesByIdResponses,
    CourseCategoryGetCourseCategoriesByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zCourseCategoryGetCourseCategoriesByIdRequest.parseAsync(
        data,
      );
    },
    responseStyle: "data",
    url: "/course-categories/{id}",
    ...options,
  });
};

export const courseCategoryPutCourseCategoriesById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CourseCategoryPutCourseCategoriesByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    CourseCategoryPutCourseCategoriesByIdResponses,
    CourseCategoryPutCourseCategoriesByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zCourseCategoryPutCourseCategoriesByIdRequest.parseAsync(
        data,
      );
    },
    responseStyle: "data",
    url: "/course-categories/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const courseSelectionGetCourseSelections = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<CourseSelectionGetCourseSelectionsRequest, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    CourseSelectionGetCourseSelectionsResponses,
    CourseSelectionGetCourseSelectionsErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zCourseSelectionGetCourseSelectionsRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/course-selections",
    ...options,
  });
};

export const courseSelectionPostCourseSelections = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CourseSelectionPostCourseSelectionsRequest, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CourseSelectionPostCourseSelectionsResponses,
    CourseSelectionPostCourseSelectionsErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zCourseSelectionPostCourseSelectionsRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/course-selections",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const courseSelectionDeleteCourseSelectionsById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CourseSelectionDeleteCourseSelectionsByIdRequest,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).delete<
    CourseSelectionDeleteCourseSelectionsByIdResponses,
    CourseSelectionDeleteCourseSelectionsByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zCourseSelectionDeleteCourseSelectionsByIdRequest.parseAsync(
        data,
      );
    },
    responseStyle: "data",
    url: "/course-selections/{id}",
    ...options,
  });
};

export const courseSelectionGetCourseSelectionsById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CourseSelectionGetCourseSelectionsByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    CourseSelectionGetCourseSelectionsByIdResponses,
    CourseSelectionGetCourseSelectionsByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zCourseSelectionGetCourseSelectionsByIdRequest.parseAsync(
        data,
      );
    },
    responseStyle: "data",
    url: "/course-selections/{id}",
    ...options,
  });
};

export const courseSelectionPutCourseSelectionsById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CourseSelectionPutCourseSelectionsByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    CourseSelectionPutCourseSelectionsByIdResponses,
    CourseSelectionPutCourseSelectionsByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zCourseSelectionPutCourseSelectionsByIdRequest.parseAsync(
        data,
      );
    },
    responseStyle: "data",
    url: "/course-selections/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const exerciseGetExercises = <ThrowOnError extends boolean = false>(
  options?: Options<ExerciseGetExercisesRequest, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ExerciseGetExercisesResponses,
    ExerciseGetExercisesErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zExerciseGetExercisesRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/exercises",
    ...options,
  });
};

export const exercisePostExercises = <ThrowOnError extends boolean = false>(
  options: Options<ExercisePostExercisesRequest, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ExercisePostExercisesResponses,
    ExercisePostExercisesErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zExercisePostExercisesRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/exercises",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const exerciseDeleteExercisesById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ExerciseDeleteExercisesByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    ExerciseDeleteExercisesByIdResponses,
    ExerciseDeleteExercisesByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zExerciseDeleteExercisesByIdRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/exercises/{id}",
    ...options,
  });
};

export const exerciseGetExercisesById = <ThrowOnError extends boolean = false>(
  options: Options<ExerciseGetExercisesByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ExerciseGetExercisesByIdResponses,
    ExerciseGetExercisesByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zExerciseGetExercisesByIdRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/exercises/{id}",
    ...options,
  });
};

export const exercisePutExercisesById = <ThrowOnError extends boolean = false>(
  options: Options<ExercisePutExercisesByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    ExercisePutExercisesByIdResponses,
    ExercisePutExercisesByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zExercisePutExercisesByIdRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/exercises/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const exerciseOptionGetExerciseOptions = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ExerciseOptionGetExerciseOptionsRequest, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ExerciseOptionGetExerciseOptionsResponses,
    ExerciseOptionGetExerciseOptionsErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zExerciseOptionGetExerciseOptionsRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/exercise-options",
    ...options,
  });
};

export const exerciseOptionPostExerciseOptions = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ExerciseOptionPostExerciseOptionsRequest, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ExerciseOptionPostExerciseOptionsResponses,
    ExerciseOptionPostExerciseOptionsErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zExerciseOptionPostExerciseOptionsRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/exercise-options",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const exerciseOptionDeleteExerciseOptionsById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ExerciseOptionDeleteExerciseOptionsByIdRequest,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).delete<
    ExerciseOptionDeleteExerciseOptionsByIdResponses,
    ExerciseOptionDeleteExerciseOptionsByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zExerciseOptionDeleteExerciseOptionsByIdRequest.parseAsync(
        data,
      );
    },
    responseStyle: "data",
    url: "/exercise-options/{id}",
    ...options,
  });
};

export const exerciseOptionGetExerciseOptionsById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ExerciseOptionGetExerciseOptionsByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ExerciseOptionGetExerciseOptionsByIdResponses,
    ExerciseOptionGetExerciseOptionsByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zExerciseOptionGetExerciseOptionsByIdRequest.parseAsync(
        data,
      );
    },
    responseStyle: "data",
    url: "/exercise-options/{id}",
    ...options,
  });
};

export const exerciseOptionPutExerciseOptionsById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ExerciseOptionPutExerciseOptionsByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    ExerciseOptionPutExerciseOptionsByIdResponses,
    ExerciseOptionPutExerciseOptionsByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zExerciseOptionPutExerciseOptionsByIdRequest.parseAsync(
        data,
      );
    },
    responseStyle: "data",
    url: "/exercise-options/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const feedbackGetFeedbacks = <ThrowOnError extends boolean = false>(
  options?: Options<FeedbackGetFeedbacksRequest, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    FeedbackGetFeedbacksResponses,
    FeedbackGetFeedbacksErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zFeedbackGetFeedbacksRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/feedbacks",
    ...options,
  });
};

export const feedbackPostFeedbacks = <ThrowOnError extends boolean = false>(
  options: Options<FeedbackPostFeedbacksRequest, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    FeedbackPostFeedbacksResponses,
    FeedbackPostFeedbacksErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zFeedbackPostFeedbacksRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/feedbacks",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const feedbackDeleteFeedbacksById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<FeedbackDeleteFeedbacksByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    FeedbackDeleteFeedbacksByIdResponses,
    FeedbackDeleteFeedbacksByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zFeedbackDeleteFeedbacksByIdRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/feedbacks/{id}",
    ...options,
  });
};

export const feedbackGetFeedbacksById = <ThrowOnError extends boolean = false>(
  options: Options<FeedbackGetFeedbacksByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    FeedbackGetFeedbacksByIdResponses,
    FeedbackGetFeedbacksByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zFeedbackGetFeedbacksByIdRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/feedbacks/{id}",
    ...options,
  });
};

export const feedbackPutFeedbacksById = <ThrowOnError extends boolean = false>(
  options: Options<FeedbackPutFeedbacksByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    FeedbackPutFeedbacksByIdResponses,
    FeedbackPutFeedbacksByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zFeedbackPutFeedbacksByIdRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/feedbacks/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const lectureGetLectures = <ThrowOnError extends boolean = false>(
  options?: Options<LectureGetLecturesRequest, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    LectureGetLecturesResponses,
    LectureGetLecturesErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zLectureGetLecturesRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/lectures",
    ...options,
  });
};

export const lecturePostLectures = <ThrowOnError extends boolean = false>(
  options: Options<LecturePostLecturesRequest, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    LecturePostLecturesResponses,
    LecturePostLecturesErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zLecturePostLecturesRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/lectures",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const lectureDeleteLecturesById = <ThrowOnError extends boolean = false>(
  options: Options<LectureDeleteLecturesByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    LectureDeleteLecturesByIdResponses,
    LectureDeleteLecturesByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zLectureDeleteLecturesByIdRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/lectures/{id}",
    ...options,
  });
};

export const lectureGetLecturesById = <ThrowOnError extends boolean = false>(
  options: Options<LectureGetLecturesByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    LectureGetLecturesByIdResponses,
    LectureGetLecturesByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zLectureGetLecturesByIdRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/lectures/{id}",
    ...options,
  });
};

export const lecturePutLecturesById = <ThrowOnError extends boolean = false>(
  options: Options<LecturePutLecturesByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    LecturePutLecturesByIdResponses,
    LecturePutLecturesByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zLecturePutLecturesByIdRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/lectures/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const passwordResetTokenGetPasswordResetTokens = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    PasswordResetTokenGetPasswordResetTokensRequest,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    PasswordResetTokenGetPasswordResetTokensResponses,
    PasswordResetTokenGetPasswordResetTokensErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zPasswordResetTokenGetPasswordResetTokensRequest.parseAsync(
        data,
      );
    },
    responseStyle: "data",
    url: "/password-reset-tokens",
    ...options,
  });
};

export const passwordResetTokenPostPasswordResetTokens = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PasswordResetTokenPostPasswordResetTokensRequest,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    PasswordResetTokenPostPasswordResetTokensResponses,
    PasswordResetTokenPostPasswordResetTokensErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zPasswordResetTokenPostPasswordResetTokensRequest.parseAsync(
        data,
      );
    },
    responseStyle: "data",
    url: "/password-reset-tokens",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const passwordResetTokenDeletePasswordResetTokensById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PasswordResetTokenDeletePasswordResetTokensByIdRequest,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).delete<
    PasswordResetTokenDeletePasswordResetTokensByIdResponses,
    PasswordResetTokenDeletePasswordResetTokensByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zPasswordResetTokenDeletePasswordResetTokensByIdRequest.parseAsync(
        data,
      );
    },
    responseStyle: "data",
    url: "/password-reset-tokens/{id}",
    ...options,
  });
};

export const passwordResetTokenGetPasswordResetTokensById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PasswordResetTokenGetPasswordResetTokensByIdRequest,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).get<
    PasswordResetTokenGetPasswordResetTokensByIdResponses,
    PasswordResetTokenGetPasswordResetTokensByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zPasswordResetTokenGetPasswordResetTokensByIdRequest.parseAsync(
        data,
      );
    },
    responseStyle: "data",
    url: "/password-reset-tokens/{id}",
    ...options,
  });
};

export const passwordResetTokenPutPasswordResetTokensById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PasswordResetTokenPutPasswordResetTokensByIdRequest,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).put<
    PasswordResetTokenPutPasswordResetTokensByIdResponses,
    PasswordResetTokenPutPasswordResetTokensByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zPasswordResetTokenPutPasswordResetTokensByIdRequest.parseAsync(
        data,
      );
    },
    responseStyle: "data",
    url: "/password-reset-tokens/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const studentGetStudents = <ThrowOnError extends boolean = false>(
  options?: Options<StudentGetStudentsRequest, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    StudentGetStudentsResponses,
    StudentGetStudentsErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zStudentGetStudentsRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/students",
    ...options,
  });
};

export const studentPostStudents = <ThrowOnError extends boolean = false>(
  options: Options<StudentPostStudentsRequest, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    StudentPostStudentsResponses,
    StudentPostStudentsErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zStudentPostStudentsRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/students",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const studentDeleteStudentsById = <ThrowOnError extends boolean = false>(
  options: Options<StudentDeleteStudentsByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    StudentDeleteStudentsByIdResponses,
    StudentDeleteStudentsByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zStudentDeleteStudentsByIdRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/students/{id}",
    ...options,
  });
};

export const studentGetStudentsById = <ThrowOnError extends boolean = false>(
  options: Options<StudentGetStudentsByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    StudentGetStudentsByIdResponses,
    StudentGetStudentsByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zStudentGetStudentsByIdRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/students/{id}",
    ...options,
  });
};

export const studentPutStudentsById = <ThrowOnError extends boolean = false>(
  options: Options<StudentPutStudentsByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    StudentPutStudentsByIdResponses,
    StudentPutStudentsByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zStudentPutStudentsByIdRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/students/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const postStudentLogin = <ThrowOnError extends boolean = false>(
  options: Options<PostStudentLoginRequest, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostStudentLoginResponses,
    unknown,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zPostStudentLoginRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/student/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const postStudentResetPasswordRequest = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostStudentResetPasswordRequestRequest, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostStudentResetPasswordRequestResponses,
    unknown,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zPostStudentResetPasswordRequestRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/student/reset-password-request",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const postStudentResetPasswordCode = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostStudentResetPasswordCodeRequest, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostStudentResetPasswordCodeResponses,
    unknown,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zPostStudentResetPasswordCodeRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/student/reset-password-code",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const patchStudentResetPasswordUpdate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchStudentResetPasswordUpdateRequest, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    PatchStudentResetPasswordUpdateResponses,
    unknown,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zPatchStudentResetPasswordUpdateRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/student/reset-password-update",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const postStudentSignup = <ThrowOnError extends boolean = false>(
  options: Options<PostStudentSignupRequest, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostStudentSignupResponses,
    unknown,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zPostStudentSignupRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/student/signup",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const postStudentSendVerificationToken = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostStudentSendVerificationTokenRequest, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostStudentSendVerificationTokenResponses,
    unknown,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zPostStudentSendVerificationTokenRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/student/send-verification-token",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const postStudentVerifyEmail = <ThrowOnError extends boolean = false>(
  options: Options<PostStudentVerifyEmailRequest, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostStudentVerifyEmailResponses,
    unknown,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zPostStudentVerifyEmailRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/student/verify-email",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const userLogGetUserLogs = <ThrowOnError extends boolean = false>(
  options?: Options<UserLogGetUserLogsRequest, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UserLogGetUserLogsResponses,
    UserLogGetUserLogsErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zUserLogGetUserLogsRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/user-logs",
    ...options,
  });
};

export const userLogPostUserLogs = <ThrowOnError extends boolean = false>(
  options: Options<UserLogPostUserLogsRequest, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    UserLogPostUserLogsResponses,
    UserLogPostUserLogsErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zUserLogPostUserLogsRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/user-logs",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const userLogDeleteUserLogsById = <ThrowOnError extends boolean = false>(
  options: Options<UserLogDeleteUserLogsByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    UserLogDeleteUserLogsByIdResponses,
    UserLogDeleteUserLogsByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zUserLogDeleteUserLogsByIdRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/user-logs/{id}",
    ...options,
  });
};

export const userLogGetUserLogsById = <ThrowOnError extends boolean = false>(
  options: Options<UserLogGetUserLogsByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    UserLogGetUserLogsByIdResponses,
    UserLogGetUserLogsByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zUserLogGetUserLogsByIdRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/user-logs/{id}",
    ...options,
  });
};

export const userLogPutUserLogsById = <ThrowOnError extends boolean = false>(
  options: Options<UserLogPutUserLogsByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    UserLogPutUserLogsByIdResponses,
    UserLogPutUserLogsByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zUserLogPutUserLogsByIdRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/user-logs/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const verificationTokenGetVerificationTokens = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    VerificationTokenGetVerificationTokensRequest,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    VerificationTokenGetVerificationTokensResponses,
    VerificationTokenGetVerificationTokensErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zVerificationTokenGetVerificationTokensRequest.parseAsync(
        data,
      );
    },
    responseStyle: "data",
    url: "/verification-tokens",
    ...options,
  });
};

export const verificationTokenPostVerificationTokens = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    VerificationTokenPostVerificationTokensRequest,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    VerificationTokenPostVerificationTokensResponses,
    VerificationTokenPostVerificationTokensErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zVerificationTokenPostVerificationTokensRequest.parseAsync(
        data,
      );
    },
    responseStyle: "data",
    url: "/verification-tokens",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const verificationTokenDeleteVerificationTokensById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    VerificationTokenDeleteVerificationTokensByIdRequest,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).delete<
    VerificationTokenDeleteVerificationTokensByIdResponses,
    VerificationTokenDeleteVerificationTokensByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zVerificationTokenDeleteVerificationTokensByIdRequest.parseAsync(
        data,
      );
    },
    responseStyle: "data",
    url: "/verification-tokens/{id}",
    ...options,
  });
};

export const verificationTokenGetVerificationTokensById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    VerificationTokenGetVerificationTokensByIdRequest,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).get<
    VerificationTokenGetVerificationTokensByIdResponses,
    VerificationTokenGetVerificationTokensByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zVerificationTokenGetVerificationTokensByIdRequest.parseAsync(
        data,
      );
    },
    responseStyle: "data",
    url: "/verification-tokens/{id}",
    ...options,
  });
};

export const verificationTokenPutVerificationTokensById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    VerificationTokenPutVerificationTokensByIdRequest,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).put<
    VerificationTokenPutVerificationTokensByIdResponses,
    VerificationTokenPutVerificationTokensByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zVerificationTokenPutVerificationTokensByIdRequest.parseAsync(
        data,
      );
    },
    responseStyle: "data",
    url: "/verification-tokens/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const contentTypeBuilderGetContentTypes = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ContentTypeBuilderGetContentTypesRequest, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ContentTypeBuilderGetContentTypesResponses,
    ContentTypeBuilderGetContentTypesErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zContentTypeBuilderGetContentTypesRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/content-types",
    ...options,
  });
};

export const contentTypeBuilderGetContentTypesByUid = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ContentTypeBuilderGetContentTypesByUidRequest, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ContentTypeBuilderGetContentTypesByUidResponses,
    ContentTypeBuilderGetContentTypesByUidErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zContentTypeBuilderGetContentTypesByUidRequest.parseAsync(
        data,
      );
    },
    responseStyle: "data",
    url: "/content-types/{uid}",
    ...options,
  });
};

export const contentTypeBuilderGetComponents = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ContentTypeBuilderGetComponentsRequest, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ContentTypeBuilderGetComponentsResponses,
    ContentTypeBuilderGetComponentsErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zContentTypeBuilderGetComponentsRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/components",
    ...options,
  });
};

export const contentTypeBuilderGetComponentsByUid = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ContentTypeBuilderGetComponentsByUidRequest, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ContentTypeBuilderGetComponentsByUidResponses,
    ContentTypeBuilderGetComponentsByUidErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zContentTypeBuilderGetComponentsByUidRequest.parseAsync(
        data,
      );
    },
    responseStyle: "data",
    url: "/components/{uid}",
    ...options,
  });
};

export const uploadPost = <ThrowOnError extends boolean = false>(
  options?: Options<UploadPostRequest, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    UploadPostResponses,
    UploadPostErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zUploadPostRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/",
    ...options,
  });
};

export const uploadGetFiles = <ThrowOnError extends boolean = false>(
  options?: Options<UploadGetFilesRequest, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UploadGetFilesResponses,
    UploadGetFilesErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zUploadGetFilesRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/files",
    ...options,
  });
};

export const uploadDeleteFilesById = <ThrowOnError extends boolean = false>(
  options: Options<UploadDeleteFilesByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    UploadDeleteFilesByIdResponses,
    UploadDeleteFilesByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zUploadDeleteFilesByIdRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/files/{id}",
    ...options,
  });
};

export const uploadGetFilesById = <ThrowOnError extends boolean = false>(
  options: Options<UploadGetFilesByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    UploadGetFilesByIdResponses,
    UploadGetFilesByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zUploadGetFilesByIdRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/files/{id}",
    ...options,
  });
};

export const i18nGetLocales = <ThrowOnError extends boolean = false>(
  options?: Options<I18nGetLocalesRequest, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    I18nGetLocalesResponses,
    I18nGetLocalesErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zI18nGetLocalesRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/locales",
    ...options,
  });
};

export const usersPermissionsGetConnect = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<UsersPermissionsGetConnectRequest, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    unknown,
    UsersPermissionsGetConnectErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zUsersPermissionsGetConnectRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/connect/(.*)",
    ...options,
  });
};

export const usersPermissionsPostAuthLocal = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UsersPermissionsPostAuthLocalRequest, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    UsersPermissionsPostAuthLocalResponses,
    UsersPermissionsPostAuthLocalErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zUsersPermissionsPostAuthLocalRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/auth/local",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const usersPermissionsPostAuthLocalRegister = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UsersPermissionsPostAuthLocalRegisterRequest, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    UsersPermissionsPostAuthLocalRegisterResponses,
    UsersPermissionsPostAuthLocalRegisterErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zUsersPermissionsPostAuthLocalRegisterRequest.parseAsync(
        data,
      );
    },
    responseStyle: "data",
    url: "/auth/local/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const usersPermissionsGetAuthByProviderCallback = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UsersPermissionsGetAuthByProviderCallbackRequest,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).get<
    UsersPermissionsGetAuthByProviderCallbackResponses,
    UsersPermissionsGetAuthByProviderCallbackErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zUsersPermissionsGetAuthByProviderCallbackRequest.parseAsync(
        data,
      );
    },
    responseStyle: "data",
    url: "/auth/{provider}/callback",
    ...options,
  });
};

export const usersPermissionsPostAuthForgotPassword = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UsersPermissionsPostAuthForgotPasswordRequest, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    UsersPermissionsPostAuthForgotPasswordResponses,
    UsersPermissionsPostAuthForgotPasswordErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zUsersPermissionsPostAuthForgotPasswordRequest.parseAsync(
        data,
      );
    },
    responseStyle: "data",
    url: "/auth/forgot-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const usersPermissionsPostAuthResetPassword = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UsersPermissionsPostAuthResetPasswordRequest, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    UsersPermissionsPostAuthResetPasswordResponses,
    UsersPermissionsPostAuthResetPasswordErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zUsersPermissionsPostAuthResetPasswordRequest.parseAsync(
        data,
      );
    },
    responseStyle: "data",
    url: "/auth/reset-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const usersPermissionsGetAuthEmailConfirmation = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    UsersPermissionsGetAuthEmailConfirmationRequest,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    UsersPermissionsGetAuthEmailConfirmationResponses,
    UsersPermissionsGetAuthEmailConfirmationErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zUsersPermissionsGetAuthEmailConfirmationRequest.parseAsync(
        data,
      );
    },
    responseStyle: "data",
    url: "/auth/email-confirmation",
    ...options,
  });
};

export const usersPermissionsPostAuthSendEmailConfirmation = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UsersPermissionsPostAuthSendEmailConfirmationRequest,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    UsersPermissionsPostAuthSendEmailConfirmationResponses,
    UsersPermissionsPostAuthSendEmailConfirmationErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zUsersPermissionsPostAuthSendEmailConfirmationRequest.parseAsync(
        data,
      );
    },
    responseStyle: "data",
    url: "/auth/send-email-confirmation",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const usersPermissionsPostAuthChangePassword = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UsersPermissionsPostAuthChangePasswordRequest, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    UsersPermissionsPostAuthChangePasswordResponses,
    UsersPermissionsPostAuthChangePasswordErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zUsersPermissionsPostAuthChangePasswordRequest.parseAsync(
        data,
      );
    },
    responseStyle: "data",
    url: "/auth/change-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const usersPermissionsPostAuthRefresh = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<UsersPermissionsPostAuthRefreshRequest, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    unknown,
    UsersPermissionsPostAuthRefreshErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zUsersPermissionsPostAuthRefreshRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/auth/refresh",
    ...options,
  });
};

export const usersPermissionsPostAuthLogout = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<UsersPermissionsPostAuthLogoutRequest, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    unknown,
    UsersPermissionsPostAuthLogoutErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zUsersPermissionsPostAuthLogoutRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/auth/logout",
    ...options,
  });
};

export const usersPermissionsGetUsersCount = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<UsersPermissionsGetUsersCountRequest, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UsersPermissionsGetUsersCountResponses,
    UsersPermissionsGetUsersCountErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zUsersPermissionsGetUsersCountRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/users/count",
    ...options,
  });
};

export const usersPermissionsGetUsers = <ThrowOnError extends boolean = false>(
  options?: Options<UsersPermissionsGetUsersRequest, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UsersPermissionsGetUsersResponses,
    UsersPermissionsGetUsersErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zUsersPermissionsGetUsersRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/users",
    ...options,
  });
};

export const usersPermissionsPostUsers = <ThrowOnError extends boolean = false>(
  options: Options<UsersPermissionsPostUsersRequest, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    UsersPermissionsPostUsersResponses,
    UsersPermissionsPostUsersErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zUsersPermissionsPostUsersRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/users",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const usersPermissionsGetUsersMe = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<UsersPermissionsGetUsersMeRequest, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UsersPermissionsGetUsersMeResponses,
    UsersPermissionsGetUsersMeErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zUsersPermissionsGetUsersMeRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/users/me",
    ...options,
  });
};

export const usersPermissionsDeleteUsersById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UsersPermissionsDeleteUsersByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    UsersPermissionsDeleteUsersByIdResponses,
    UsersPermissionsDeleteUsersByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zUsersPermissionsDeleteUsersByIdRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/users/{id}",
    ...options,
  });
};

export const usersPermissionsGetUsersById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UsersPermissionsGetUsersByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    UsersPermissionsGetUsersByIdResponses,
    UsersPermissionsGetUsersByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zUsersPermissionsGetUsersByIdRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/users/{id}",
    ...options,
  });
};

export const usersPermissionsPutUsersById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UsersPermissionsPutUsersByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    UsersPermissionsPutUsersByIdResponses,
    UsersPermissionsPutUsersByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zUsersPermissionsPutUsersByIdRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/users/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const usersPermissionsGetRolesById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UsersPermissionsGetRolesByIdRequest, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    UsersPermissionsGetRolesByIdResponses,
    UsersPermissionsGetRolesByIdErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zUsersPermissionsGetRolesByIdRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/roles/{id}",
    ...options,
  });
};

export const usersPermissionsGetRoles = <ThrowOnError extends boolean = false>(
  options?: Options<UsersPermissionsGetRolesRequest, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UsersPermissionsGetRolesResponses,
    UsersPermissionsGetRolesErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zUsersPermissionsGetRolesRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/roles",
    ...options,
  });
};

export const usersPermissionsPostRoles = <ThrowOnError extends boolean = false>(
  options?: Options<UsersPermissionsPostRolesRequest, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    UsersPermissionsPostRolesResponses,
    UsersPermissionsPostRolesErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zUsersPermissionsPostRolesRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/roles",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

export const usersPermissionsDeleteRolesByRole = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UsersPermissionsDeleteRolesByRoleRequest, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    UsersPermissionsDeleteRolesByRoleResponses,
    UsersPermissionsDeleteRolesByRoleErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zUsersPermissionsDeleteRolesByRoleRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/roles/{role}",
    ...options,
  });
};

export const usersPermissionsPutRolesByRole = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UsersPermissionsPutRolesByRoleRequest, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    UsersPermissionsPutRolesByRoleResponses,
    UsersPermissionsPutRolesByRoleErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zUsersPermissionsPutRolesByRoleRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/roles/{role}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const usersPermissionsGetPermissions = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<UsersPermissionsGetPermissionsRequest, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UsersPermissionsGetPermissionsResponses,
    UsersPermissionsGetPermissionsErrors,
    ThrowOnError,
    "data"
  >({
    requestValidator: async (data) => {
      return await zUsersPermissionsGetPermissionsRequest.parseAsync(data);
    },
    responseStyle: "data",
    url: "/permissions",
    ...options,
  });
};
